# See https://cloud.google.com/appengine/docs/flexible/nodejs/reference/app-yaml

runtime: nodejs
env: flex

skip_files:
  - ^node_modules$
  - ^converter$
  - ^notebooks/(?!toc.yaml)$
  - ^venv$
  - ^test$
  - ^.git$
  - ^.idea$

handlers:
  - url: /.*
    script: app.js

resources:
  cpu: 1
  memory_gb: 1

liveness_check:
  path: "/health"

readiness_check:
  path: "/health"

secure: always
