name: base
channels:
- conda-forge
dependencies:
- python==3.8.*
- pip==20.*
- cython
- numpy
- matplotlib-base
- qutip
- sympy
- pylatexenc
- numexpr
- pip:
  - pandas
  - qiskit
  - ./qiskit-textbook-src
  - ibm_quantum_widgets
